export const TYPES = {
    AmadeusService: Symbol("AmadeusService"),
    CryptographyService: Symbol("CryptographyService"),
    ExchangeService: Symbol("ExchangeService"),
    FeeService: Symbol("FeeService"),
    JobRunner: Symbol("JobRunner"),
    LiquidityService: Symbol("LiquidityService"),
    LoggerService: Symbol("LoggerService"),
    OrderService: Symbol("OrderService"),
    RequestLimitService: Symbol("RequestLimitService"),
    SaltService: Symbol("SaltService"),
    TickerService: Symbol("TickerService"),
    TimeService: Symbol("TimeService"),
    TokenPairsService: Symbol("TokenPairsService"),
    TokenService: Symbol("TokenService"),
    ValidationService: Symbol("ValidationService"),
};
