export const TYPES = {
    AmadeusService: Symbol("AmadeusService"),
    CryptographyService: Symbol("CryptographyService"),
    ExchangeService: Symbol("ExchangeService"),
    FeeService: Symbol("FeeService"),
    JobRunner: Symbol("JobRunner"),
    JobTask: Symbol("JobTask"),
    LiquidityService: Symbol("LiquidityService"),
    LoggerService: Symbol("LoggerService"),
    OrderFactory: Symbol("OrderFactory"),
    OrderRelayerUrl: Symbol("OrderRelayerUrl"),
    OrderService: Symbol("OrderService"),
    PostOrderService: Symbol("PostOrderService"),
    PriceService: Symbol("PriceService"),
    RequestLimitService: Symbol("RequestLimitService"),
    SaltService: Symbol("SaltService"),
    TickerFactory: Symbol("TickerFactory"),
    TickerRelayerUrl: Symbol("TickerRelayerUrl"),
    TickerRepository: Symbol("TickerRepository"),
    TickerService: Symbol("TickerService"),
    TimeService: Symbol("TimeService"),
    TokenPairsService: Symbol("TokenPairsService"),
    TokenService: Symbol("TokenService"),
    ValidationService: Symbol("ValidationService"),
};
